### ISSUE TITLE
Not working on debian sid

### ISSUE THREAD

**Issue by y0va** [siman-man/typogen#3]
```
 $ sudo gem install typogen
Fetching: typogen-0.2.1.gem (100%)
Successfully installed typogen-0.2.1
Parsing documentation for typogen-0.2.1
Installing ri documentation for typogen-0.2.1
Done installing documentation for typogen after 0 seconds
1 gem installed
 $ typogen
Traceback (most recent call last):
	5: from /usr/local/bin/typogen:23:in `<main>'
	4: from /usr/local/bin/typogen:23:in `load'
	3: from /var/lib/gems/2.5.0/gems/typogen-0.2.1/exe/typogen:20:in `<top (required)>'
	2: from /var/lib/gems/2.5.0/gems/typogen-0.2.1/lib/typogen/cli.rb:4:in `run'
	1: from /var/lib/gems/2.5.0/gems/typogen-0.2.1/lib/typogen/typo.rb:9:in `create'
/var/lib/gems/2.5.0/gems/typogen-0.2.1/lib/typogen/skip_letter.rb:4:in `create': undefined method `size' for nil:NilClass (NoMethodError)
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

**Comment by siman-man** [comment]
Thanks report!

`typogen` don't supported no command arguments pattern. (until 0.2.1)
but, I fixed this issue! (from 0.2.2)

now, is shown help messages.

```
$ typogen
Usage: typogen [options] word
    -v, --version                    display the typogen version.
```
